[package]
name = "pong-rs"
version = "0.1.0"
authors = ["Justin Sacbibit <jsacbibit@gmail.com>"]

[dependencies]
piston = "0.4.1"
piston2d-graphics = "0.4.1"
pistoncore-glutin_window = "0.5.0"
piston2d-opengl_graphics = "0.6.0"

